### ISSUE TITLE
Device no longer reboots after config change and no file is written

### ISSUE THREAD

**Issue by Cdetviler** [aprsworld/piNetConfig#1]
I have only briefly gone over your changes last night, but I think I know where the problem is originating. It looks like you are using a new function 'config-write' in order to write to the interfaces file. That function has two arguments, the `config` and the `file` to write to. When you are calling it on line 9 of netconfig.php, you are only passing the `config`. I tried passing the path to my temporary file and it seems to work then.

It is also not rebooting, I think you forgot to call system($reboot) at the end of this new function. That is how you were doing it before if I remember correctly.

**Comment by davarus** [comment]
Issue is resolved.  The php file that handles both output of current settings and config and to update the config is now just netconfig.php.  In addition, the configuration on POST should be wrapped in a "config" object mirroring the output.
